# Generated by Django 5.2.9 on 2025-12-04 17:57

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Сумма выплаты (должна быть больше 0)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Сумма выплаты",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("RUB", "Российский рубль"),
                            ("USD", "Доллар США"),
                            ("EUR", "Евро"),
                            ("GBP", "Фунт стерлингов"),
                        ],
                        default="RUB",
                        max_length=3,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        help_text="Полное имя или название организации получателя",
                        max_length=255,
                        verbose_name="Имя получателя",
                    ),
                ),
                (
                    "recipient_account",
                    models.CharField(
                        help_text="Банковский счет, номер карты или другой идентификатор",
                        max_length=100,
                        verbose_name="Номер счета получателя",
                    ),
                ),
                (
                    "recipient_bank",
                    models.CharField(
                        blank=True,
                        help_text="Название банка получателя (опционально)",
                        max_length=255,
                        verbose_name="Банк получателя",
                    ),
                ),
                (
                    "recipient_bank_code",
                    models.CharField(
                        blank=True,
                        help_text="БИК, SWIFT или другой код банка (опционально)",
                        max_length=50,
                        verbose_name="БИК/SWIFT банка",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает обработки"),
                            ("processing", "В обработке"),
                            ("approved", "Одобрена"),
                            ("rejected", "Отклонена"),
                            ("completed", "Выполнена"),
                            ("cancelled", "Отменена"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Статус заявки",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительная информация о выплате",
                        verbose_name="Описание/Комментарий",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Дата и время обработки заявки",
                        null=True,
                        verbose_name="Дата обработки",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Причина отклонения заявки (если применимо)",
                        verbose_name="Причина отклонения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на выплату",
                "verbose_name_plural": "Заявки на выплату",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at", "status"],
                        name="request_pay_created_247123_idx",
                    ),
                    models.Index(
                        fields=["recipient_account"],
                        name="request_pay_recipie_cf0a6e_idx",
                    ),
                ],
            },
        ),
    ]
